apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2023-06-09T21:02:28Z","generation":1,"labels":{"app":"arlingtonthisweek"},"name":"arlingtonthisweek","namespace":"default","resourceVersion":"6590","uid":"9f71e797-4d38-468b-b037-f1437fa624df"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"arlingtonthisweek"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"arlingtonthisweek"}},"spec":{"containers":[{"image":"chrisbbehrens/arlingtonthisweekweb","imagePullPolicy":"Always","name":"arlingtonthisweekweb","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2023-06-09T21:02:36Z","lastUpdateTime":"2023-06-09T21:02:36Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2023-06-09T21:02:28Z","lastUpdateTime":"2023-06-09T21:02:36Z","message":"ReplicaSet \"arlingtonthisweek-69bb48d44d\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2023-06-09T21:02:28Z"
  generation: 2
  labels:
    app: arlingtonthisweek
  name: arlingtonthisweek
  namespace: default
  resourceVersion: "8537"
  uid: 9f71e797-4d38-468b-b037-f1437fa624df
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: arlingtonthisweek
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: arlingtonthisweek
    spec:
      containers:
      - image: chrisbbehrens/arlingtonthisweekweb
        imagePullPolicy: Always
        name: arlingtonthisweekweb
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
            - containerPort: 80
      - image: redislabs/redis
        imagePullPolicy: Always
        name: rediscache
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File        
        ports:
           - containerPort: 6379
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-06-09T21:02:36Z"
    lastUpdateTime: "2023-06-09T21:02:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-06-09T21:02:28Z"
    lastUpdateTime: "2023-06-09T21:02:36Z"
    message: ReplicaSet "arlingtonthisweek-69bb48d44d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
